In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


## Introduction to Tensors

### Creating tensors
PyTorch tensors are created using `torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Number of pairs of closing square brackets
vector.ndim

1

In [8]:
# 2 x 1 elements
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 1]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 1]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 1]])

In [18]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 1]],
                       [[0, 0, 0],
                        [1, 1, 1],
                        [2, 2, 2]],
                       [[3, 3, 3],
                        [4, 4, 4],
                        [5, 5, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 1]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[3, 3, 3],
         [4, 4, 4],
         [5, 5, 5]]])

In [19]:
TENSOR[1]

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

### Random tensors
Why random tensors?
Random tensors are important because the way many neural networks learn is starting with tensors full of random numbers, and adjust those random numbers to better represent the data.
`Start with random numbers -> look at data -> update random numbers -> loook at data -> update random numbers`

In [20]:
# Create a random tensor of size/shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1555, 0.5391, 0.6853, 0.9692],
        [0.2144, 0.8932, 0.2269, 0.7928],
        [0.2940, 0.7805, 0.4120, 0.7312]])

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigh, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
# Create my own random tensor
my_random_tensor = torch.rand(5, 4, 3)
my_random_tensor.ndim, my_random_tensor.shape

(3, torch.Size([5, 4, 3]))

In [23]:
my_random_tensor

tensor([[[0.6881, 0.6163, 0.7800],
         [0.2738, 0.7184, 0.4442],
         [0.9759, 0.5282, 0.9047],
         [0.5727, 0.9123, 0.4838]],

        [[0.2001, 0.5569, 0.2955],
         [0.4140, 0.3122, 0.9315],
         [0.8587, 0.2884, 0.2025],
         [0.4687, 0.2610, 0.3543]],

        [[0.0419, 0.6304, 0.5601],
         [0.5214, 0.4703, 0.0258],
         [0.1709, 0.8161, 0.3328],
         [0.3259, 0.2707, 0.5339]],

        [[0.7720, 0.7823, 0.9782],
         [0.5933, 0.6429, 0.0302],
         [0.8999, 0.5718, 0.3407],
         [0.7932, 0.4882, 0.3468]],

        [[0.4324, 0.3731, 0.4260],
         [0.7380, 0.9000, 0.1185],
         [0.3989, 0.3785, 0.8525],
         [0.3228, 0.8377, 0.3443]]])

### Zeros and ones

In [24]:
# Create a tensor of all zeros (for a mask)
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Element-wise multiplication
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [29]:
# Use torch.arange() to create a 1-D tensor
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note:** Tensor dataypes is one of the 3 big erros you'll run into with PyTorch & deeplearning:
1. Tensors not right dataype
2. Tensors not right shape
3. Tensors not on the right device

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what dataype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on ('cpu' by default)
                               requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [38]:
long_tensor = torch.tensor([3,6,9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1124, 0.1345, 0.3117, 0.3223],
        [0.3558, 0.8244, 0.8372, 0.7630],
        [0.7450, 0.5291, 0.4293, 0.9296]])

In [40]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1124, 0.1345, 0.3117, 0.3223],
        [0.3558, 0.8244, 0.8372, 0.7630],
        [0.7450, 0.5291, 0.4293, 0.9296]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [41]:
gpu_tensor = some_tensor.to(device="mps")
gpu_tensor

tensor([[0.1124, 0.1345, 0.3117, 0.3223],
        [0.3558, 0.8244, 0.8372, 0.7630],
        [0.7450, 0.5291, 0.4293, 0.9296]], device='mps:0')

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [42]:
# Create a tensor and add 10 to each of its elements
tensor = torch.tensor([1,2,3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [43]:
# Multiply tensor by 10
tensor * 10

tensor([110, 120, 130])

In [44]:
# Subtract 10 from tensor
tensor - 10

tensor([1, 2, 3])

In [45]:
# Try out PyTorch in-built functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([110, 120, 130])
tensor([21, 22, 23])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3, 2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dumensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [46]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.2901, 0.3032],
        [0.9388, 0.7472]])

In [47]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.0466, 0.2620, 0.2029],
        [0.1242, 0.7067, 0.8123],
        [0.1306, 0.7472, 0.9762]])

In [48]:
torch.matmul(torch.rand(3,100), torch.rand(100,3))

tensor([[29.6966, 25.5935, 27.1705],
        [29.3966, 25.6565, 26.0723],
        [29.9620, 26.6068, 27.7834]])

In [49]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals: tensor([121, 144, 169])


In [50]:
# Matrix multiplication (dot product)
print(tensor @ tensor)
print(torch.matmul(tensor, tensor))

tensor(434)
tensor(434)


In [51]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 337 μs, sys: 604 μs, total: 941 μs
Wall time: 1.1 ms


tensor(434)

In [52]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 188 μs, sys: 212 μs, total: 400 μs
Wall time: 376 μs


tensor(434)

### One of the most common errors in deep learning: shape errors
To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**.<br>
A **transpose** switches the axes or dimensions of a given tensor.

In [53]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
print(f"tensor_A = {tensor_A}\n")
print(f"tensor_A.T = {tensor_A.T}\n")

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
print(f"tensor_B = {tensor_B}\n")
print(f"tensor_B.T = {tensor_B.T}\n")

# Matrix multiplication short-hand - not we'll have to transpose tensor_B to multiply them to make the dimensions consistent
print(f"tensor_A x tensor_B.T = {torch.mm(tensor_A, tensor_B.T)}\n")
print(f"tensor_A.T x tensor_B = {torch.mm(tensor_A.T, tensor_B)}\n")
print(f"tensor_B x tensor_A.T = {torch.mm(tensor_B, tensor_A.T)}\n")
print(f"tensor_B.T x tensor_A = {torch.mm(tensor_B.T, tensor_A)}")

tensor_A = tensor([[1, 2],
        [3, 4],
        [5, 6]])

tensor_A.T = tensor([[1, 3, 5],
        [2, 4, 6]])

tensor_B = tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

tensor_B.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])

tensor_A x tensor_B.T = tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

tensor_A.T x tensor_B = tensor([[ 76, 103],
        [100, 136]])

tensor_B x tensor_A.T = tensor([[ 27,  61,  95],
        [ 30,  68, 106],
        [ 33,  75, 117]])

tensor_B.T x tensor_A = tensor([[ 76, 100],
        [103, 136]])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [66]:
# Create a tensor
x = torch.arange(1, 101, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [67]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [68]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [69]:
# Find the mean (note that torch.mean() function requires a tensor of float32 datatype to work)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [70]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [71]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [72]:
# Index of where the minimum value occurs in the tensor
x.argmin()

tensor(0)

In [73]:
x.argmax()

tensor(9)

In [74]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [80]:
# Let's create a tensor
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [81]:
# Add an extra dimension
x_reshaped = x.reshape(3, 4) # Product must preserve number of raw elements
x_reshaped

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [83]:
# Change the view
z = x.view(4, 3)
z, z.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [84]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.],
         [ 5.,  5.,  6.],
         [ 5.,  8.,  9.],
         [ 5., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]))

In [85]:
# Stack tensors on top of each other (must be the same size)
# vstack
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
        [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
        [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
        [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]])

In [86]:
# hstack
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 5.,  5.,  5.,  5.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [ 5.,  5.,  5.,  5.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [88]:
x = torch.tensor(1)
x = x.unsqueeze(dim=0)
x

tensor([1])

In [89]:
x = x.squeeze()
x

tensor(1)

In [93]:
x = torch.zeros(2,1,2,1,2)
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [94]:
y = torch.squeeze(x)
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [96]:
y = torch.squeeze(x, 0)
y, y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [97]:
y = torch.squeeze(x, 1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [98]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {y}")
print(f"Previous shape: {y.shape}")

# Add an extra dimension with unsqueeze
y_unsqueezed = y.unsqueeze(dim=0)
print(f"Current target: {y_unsqueezed}")
print(f"Current shape: {y_unsqueezed.shape}")

Previous target: tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])
Previous shape: torch.Size([2, 2, 1, 2])
Current target: tensor([[[[[0., 0.]],

          [[0., 0.]]],


         [[[0., 0.]],

          [[0., 0.]]]]])
Current shape: torch.Size([1, 2, 2, 1, 2])


In [99]:
y_unsqueezed = y.unsqueeze(dim=1)
y_unsqueezed, y_unsqueezed.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [101]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previousshape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previousshape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [104]:
# THIS IS A VIEW - SHARES THE SAME MEMORY
print(x_original[0, 0, 0])
print(x_permuted[0, 0, 0])
x_permuted[0, 0, 0] = 5
print(x_original[0, 0, 0])
print(x_permuted[0, 0, 0])

tensor(0.7894)
tensor(0.7894)
tensor(5.)
tensor(5.)


### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [106]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [107]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [109]:
# Let's index on the middle bracket (dim=1)
x[0][0] # x[0, 0]

tensor([1, 2, 3])

In [110]:
# Let's index on the last bracket (last dimension)
x[0][0][0]

tensor(1)

In [111]:
x[0][1][1]

tensor(5)

In [112]:
x[0][2][2]

tensor(9)

In [113]:
# You can use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [114]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [116]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]
# tensor([5])
# versus: x[0,1,1] = tensor(5)

tensor([5])

In [118]:
# Get index 0 of 0th and 1st dimension, and all values of 2nd dimension
x[0, 0, :]
# tensor([1, 2, 3])

tensor([1, 2, 3])

In [121]:
print(x[0, :, 2])
# tensor([3, 6, 9])
print(x[:, :, 2])
# tensor([[3, 6, 9]])

tensor([3, 6, 9])
tensor([[3, 6, 9]])


### PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [127]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
# PyTorch reflects numpy's default dataype of float64 unless specified otherwise
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [123]:
array.dtype

dtype('float64')

In [124]:
# PyTorch has different default data type...
torch.arange(1.0, 8.0).dtype

torch.float32

In [126]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [128]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [129]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [130]:
numpy_tensor.dtype

dtype('float32')

In [131]:
# Change to tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random our of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random mnumbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [134]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
# The following ACTUALLY returns a tensor!!!
print(random_tensor_A == random_tensor_B)

tensor([[0.8418, 0.5917, 0.7267, 0.9353],
        [0.5689, 0.8473, 0.2630, 0.5286],
        [0.8916, 0.4249, 0.6804, 0.8515]])
tensor([[0.9753, 0.8558, 0.0179, 0.3367],
        [0.1399, 0.7644, 0.6066, 0.6212],
        [0.3613, 0.7766, 0.2290, 0.1169]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [136]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # (gotta call each time...)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers

#### 1. Getting a GPU
1. Easiest - Use Google Colab for a free GPU (options to upgrade)
2. Use your own GPU - lots of work...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

In [137]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [142]:
# Count the number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [140]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# I'm on a Mac, so here's my option for a GPU
tensor_on_gpu = tensor.to("mps")
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

### 4. Moving tensors back to the CPU

In [143]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu.numpy()

array([1, 2, 3])