# 00. PyTorch Fundamentals Exercises
## Source: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
first_random_tensor = torch.rand(7,7)
first_random_tensor

tensor([[0.7644, 0.5420, 0.0445, 0.1515, 0.1593, 0.4104, 0.8343],
        [0.5839, 0.5749, 0.1539, 0.1370, 0.6149, 0.8423, 0.4977],
        [0.1399, 0.8605, 0.4962, 0.6302, 0.0655, 0.7810, 0.3348],
        [0.3291, 0.1758, 0.6749, 0.9782, 0.5794, 0.0204, 0.2266],
        [0.9760, 0.4007, 0.7527, 0.0599, 0.2732, 0.3733, 0.2280],
        [0.9234, 0.8805, 0.2471, 0.9854, 0.5076, 0.3599, 0.5796],
        [0.9056, 0.3915, 0.8161, 0.2259, 0.7442, 0.9994, 0.9859]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
second_random_tensor = torch.rand(1,7)

# Perform matrix multiplication 
product = torch.matmul(first_random_tensor, second_random_tensor.T)
product

tensor([[1.7359],
        [1.9397],
        [1.9746],
        [1.4365],
        [2.2263],
        [2.3970],
        [3.0469]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
first_random_tensor = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
second_random_tensor = torch.rand(1,7)

# Matrix multiply tensors
product = torch.matmul(first_random_tensor, second_random_tensor.T)
product

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
RANDOM_SEED = 1234


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
torch.mps.manual_seed(RANDOM_SEED)

# Check for access to GPU
# N/A - I'm on a MAC

# Create two random tensors on GPU
first_random_tensor = torch.rand((2, 3), device='mps')

torch.mps.manual_seed(RANDOM_SEED)
second_random_tensor = torch.rand((2, 3), device='mps')

first_random_tensor, second_random_tensor

(tensor([[0.3664, 0.0755, 0.7784],
         [0.1186, 0.7737, 0.1323]], device='mps:0'),
 tensor([[0.3664, 0.0755, 0.7784],
         [0.1186, 0.7737, 0.1323]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
product = torch.matmul(first_random_tensor, second_random_tensor.T)
product

tensor([[0.7459, 0.2049],
        [0.2049, 0.6302]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
max_value = product.max()

# Find min
min_value = product.min()

max_value, min_value

(tensor(0.7459, device='mps:0'), tensor(0.2049, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
max_index = product.argmax()

# Find arg min
min_index = product.argmin()

max_index, min_index

(tensor(0, device='mps:0'), tensor(1, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = random_tensor.squeeze()

# Print out tensors and their shapes
random_tensor, random_tensor.shape, squeezed_tensor, squeezed_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))